package shared;

public enum Request {
    CREATEACCOUNT,
    CREATEACCOUNTSUCCES,
    CREATEACCOUNTFAIL,
    AUTHENTIFICATION,
    AUTHENTICATIONFAIL,
    AUTHENTIFICATIONRIGHT,
    CLOSE,
    TOPICSELECTION,
    MESSAGE,
}
